### PR TITLE
Update pytest

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this expands #5 with my findings

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus ping - do you by chance have a quick idea for

```
est_example.py FE                                                       [100%]Traceback (most recent call last):
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/bin/py.test", line 8, in <module>
    sys.exit(console_main())
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/_pytest/config/__init__.py", line 180, in console_main
    code = main()
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/_pytest/config/__init__.py", line 158, in main
    config=config
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/_pytest/main.py", line 289, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/_pytest/main.py", line 278, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/_pytest/terminal.py", line 803, in pytest_sessionfinish
    outcome.get_result()
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/_pytest/runner.py", line 94, in pytest_sessionfinish
    session._setupstate.teardown_all()
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/_pytest/runner.py", line 397, in teardown_all
    self._teardown_with_finalization(key)
  File "~/Projects/pytest-subtesthack/.tox/py36-pytest60/lib/python3.6/site-packages/_pytest/runner.py", line 391, in _teardown_with_finalization
    assert colitem in self.stack
AssertionError
```

**Comment by nicoddemus** [comment]
Seems something really messed up the setup/teardown stack somehow (I'm sure you know that already), but nothing comes to mind in pytest 6 that might have caused this...

**Comment by MeggyCal** [comment]
This failure looks like https://github.com/pytest-dev/pytest/issues/7724 (still open). Could it be the same issue?

**Comment by RonnyPfannschmidt** [comment]
right now i wouldnt bet on that

i believe its pytest getting confused about function scopes as this plugin messes with functions within functions

im still not sure about the exact cause
we may need to integrate better with the stack

tagging @bluetech as he may have a idea

**Comment by bluetech** [comment]
With pytest master there is a better stack trace. BTW I had to apply some changes for hypothesis to work:

```diff
diff --git a/test_example.py b/test_example.py
index d4abb24..02884c3 100644
--- a/test_example.py
+++ b/test_example.py
@@ -1,12 +1,13 @@
 import pytest
 
-from hypothesis import given
+from hypothesis import given, settings, HealthCheck
 from hypothesis.strategies import text
 
 @pytest.fixture(scope='module')
 def thing():
     return object()
 
+@settings(suppress_health_check=[HealthCheck.function_scoped_fixture])
 @given(s=text())
 def test_foo(thing, subtest, s):
     outer_thing = thing
```

The problem is that before the `subtest` fixture `item.ihook.pytest_runtest_setup(item=item)` call, the SetupState stack looks like this:

```
<Session>
<Module test_example.py>
<Function test_foo>
```

But the subtest node hierarchy is defined as

```
<Session>
<Module test_example.py>
<Function test_foo[]>
```

Because of the `parent=parent_test.parent` line. So this is incompatible with the existing stack -- `<Function test_foo>` is not in the node hierarchy but hasn't been torn down -- so the assert triggers.

The fix is to change `parent=parent_test.parent` to ``parent=parent_test`, unless it causes other problems.

**Comment by untitaker** [comment]
not sure why this works now, but will merge in a bit

**Pull request merged**
